### ISSUE TITLE
Remove jayson dependency since not ESM

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/eos-evm-miner#2]
- [x] must be ESM compatible
- [x] must work with bun

```
$ bun ./bin/cli.ts start
[0.06ms] ".env"
1071 |   _dispatchSubcommand(commandName, operands, unknown) {
1072 |     const subCommand = this._findCommand(commandName);
1073 |     if (!subCommand) this.help({ error: true });
1074 | 
1075 |     let hookResult;
1076 |     hookResult = this._chainOrCallSubCommandHook(hookResult, subCommand, 'preSubcommand');
                     ^
ReferenceError: Cannot access uninitialized variable.
      at _dispatchSubcommand (/Users/denis/Github/eos-evm-miner/node_modules/commander/lib/command.js:1076:17)
      at parse (/Users/denis/Github/eos-evm-miner/node_modules/commander/lib/command.js:909:4)
      at /Users/denis/Github/eos-evm-miner/bin/cli.ts:29:0
```

**Comment by DenisCarriere** [comment]
Converted entire project to use bun
